import type { Nation, Fief, MapTerrainFeature } from '../types/worldMap'

export const CONTINENT_NAME = '칼라드리아 대륙 (Continent of Caladria)'
export const MAP_WIDTH = 1800
export const MAP_HEIGHT = 1200

export const NATIONS: Record<string, Nation> = {
  kingdom_luminas: {
    id: 'kingdom_luminas',
    name: '루미나스 왕국',
    type: 'kingdom',
    typeLabel: '봉건 왕국 (플레이어 소속국)',
    color: '#1d4ed8',
    accentColor: '#60a5fa',
    emblem: '👑',
    capital: '성왕도 에텔가르드',
    ruler: '국왕 에드워드 4세',
    relation: 'liege',
    relationLabel: '종주국 (내 주군)',
    militaryPower: 'A (기사단 & 중장보병)',
    economyPower: 'A (비옥한 곡창지대)',
    description:
      '유구한 역사와 기사도 전통을 자랑하는 대륙 중앙의 왕국. 플레이어가 충성을 맹세하고 동부 변경 개척지를 분봉받은 모국입니다.',
    territoryPoints: [
      [520, 360],
      [920, 360],
      [960, 720],
      [780, 840],
      [480, 740],
      [440, 520],
    ],
  },
  valdor_empire: {
    id: 'valdor_empire',
    name: '발도르 철혈 제국',
    type: 'empire',
    typeLabel: '군사 제국',
    color: '#991b1b',
    accentColor: '#f87171',
    emblem: '🦅',
    capital: '검은 요새 바란하임',
    ruler: '철혈 황제 블라디미르 1세',
    relation: 'wary',
    relationLabel: '경계 및 군사 긴장',
    militaryPower: 'S (대규모 흑철기병단)',
    economyPower: 'B+ (제철소 & 징집령)',
    description:
      '북서부 험준한 산악과 평원을 지배하는 호전적인 군사 제국. 루미나스 왕국의 국경을 끊임없이 위협하며 기회를 엿보고 있습니다.',
    territoryPoints: [
      [100, 100],
      [680, 100],
      [640, 420],
      [420, 480],
      [140, 560],
    ],
  },
  free_republic: {
    id: 'free_republic',
    name: '자유 항만 공화국 연합',
    type: 'republic',
    typeLabel: '상인 공화국',
    color: '#b45309',
    accentColor: '#fbbf24',
    emblem: '⚖️',
    capital: '베네치아 자유항',
    ruler: '대의원 의장 카스파 론',
    relation: 'neutral',
    relationLabel: '중립 (통상 협정)',
    militaryPower: 'B (사설 용병단 & 해군)',
    economyPower: 'S+ (대륙 최고의 상업 자본)',
    description:
      '남부 해안선을 따라 형성된 7개 항구 도시들의 자치 연합. 거대한 무역 상단과 황금으로 막강한 영향력을 행사합니다.',
    territoryPoints: [
      [220, 740],
      [640, 780],
      [600, 1120],
      [160, 1100],
    ],
  },
  sylvana_federation: {
    id: 'sylvana_federation',
    name: '실바나 대삼림 연방',
    type: 'federation',
    typeLabel: '자치 연방',
    color: '#065f46',
    accentColor: '#34d399',
    emblem: '🌿',
    capital: '세계수 텔드라실',
    ruler: '대장로 엘로라 에델',
    relation: 'allied',
    relationLabel: '우호 및 친선',
    militaryPower: 'A- (정령 마법사 & 삼림 순찰대)',
    economyPower: 'B (희귀 약초, 비단, 원목)',
    description:
      '동부의 신비로운 원시림에 정착한 엘프와 수인 종족의 평화 연방. 플레이어의 개척 영지와 동쪽 숲 국경을 평화롭게 접하고 있습니다.',
    territoryPoints: [
      [980, 240],
      [1680, 200],
      [1720, 680],
      [1120, 740],
      [960, 460],
    ],
  },
  solaris_holy_empire: {
    id: 'solaris_holy_empire',
    name: '솔라리스 신성 황국',
    type: 'holy_empire',
    typeLabel: '신정 황국',
    color: '#6b21a8',
    accentColor: '#c084fc',
    emblem: '☀️',
    capital: '성도 솔라리아',
    ruler: '교황 루시우스 3세',
    relation: 'neutral',
    relationLabel: '배타적 중립',
    militaryPower: 'A+ (광휘의 성기사단)',
    economyPower: 'A (신도 헌금 및 성유물 교역)',
    description:
      '대륙 남동부를 성역화하여 다스리는 종교 황국. 태양의 교리를 따르며 타국의 분쟁에는 관여하지 않으나 막강한 성기사단을 보유하고 있습니다.',
    territoryPoints: [
      [760, 840],
      [1480, 820],
      [1520, 1120],
      [780, 1140],
    ],
  },
}

export const FIEFS: Fief[] = [
  // 1. Player Fief
  {
    id: 'my_world_fief',
    name: '🏰 MY-WORLD 영지',
    nationId: 'kingdom_luminas',
    type: 'player',
    x: 820,
    y: 540,
    rulerName: '플레이어 (개척 영주)',
    title: '루미나스 왕국 변경 개척 영주',
    level: 1,
    defense: 25,
    economy: 30,
    specialty: '광산 채굴, 미개척지 영토 확장, 몬스터 토벌 방벽',
    description:
      '플레이어가 하사받은 루미나스 왕국 동부 국경의 개척 영지. 인근의 실바나 삼림과 북쪽 제국 국경 사이에 위치해 있으며, 위험한 몬스터를 몰아내고 부지를 넓혀가고 있는 신흥 전략 거점입니다.',
  },
  // 2. Neighboring Fiefs in the Kingdom
  {
    id: 'fief_heylun',
    name: '하일룬 백작령',
    nationId: 'kingdom_luminas',
    type: 'neighbor',
    x: 640,
    y: 560,
    rulerName: '레오나르도 백작',
    title: '서부 곡창지대 영주',
    level: 3,
    defense: 45,
    economy: 65,
    specialty: '황금 밀, 우수한 군마, 식량 수출',
    description:
      '플레이어 영지의 바로 서쪽에 인접한 풍요로운 영지. 플레이어 영지와 가장 가까우며 안정적인 식량 무역로 역할을 담당합니다.',
  },
  {
    id: 'fief_karkas',
    name: '카르카스 자작령',
    nationId: 'kingdom_luminas',
    type: 'neighbor',
    x: 770,
    y: 420,
    rulerName: '발타자르 자작',
    title: '북부 철광 산맥 수비대장',
    level: 3,
    defense: 60,
    economy: 40,
    specialty: '철광석 광산, 대장간 병기, 척후병',
    description:
      '플레이어 영지 북쪽의 바위산 일대를 다스리는 강인한 산악 영지. 발도르 제국의 남하를 1차로 감시하는 파수꾼 역할을 맡고 있습니다.',
  },
  {
    id: 'fief_blackforest',
    name: '검은숲 변경백령',
    nationId: 'kingdom_luminas',
    type: 'neighbor',
    x: 870,
    y: 690,
    rulerName: '로이드 변경백',
    title: '야생 몬스터 방어선 사령관',
    level: 4,
    defense: 75,
    economy: 35,
    specialty: '몬스터 수렵 전문가, 모피, 중장 방벽',
    description:
      '플레이어 영지의 남동쪽에 위치한 요새 영지. 고블린과 오크 등 위험한 야생 생물 군단을 틀어막는 최전선 베테랑 방어선입니다.',
  },
  {
    id: 'capital_luminas',
    name: '👑 성왕도 에텔가르드',
    nationId: 'kingdom_luminas',
    type: 'capital',
    x: 680,
    y: 480,
    rulerName: '국왕 에드워드 4세',
    title: '루미나스 왕국의 주권자',
    level: 5,
    defense: 95,
    economy: 90,
    specialty: '왕실 기사단, 대마법탑, 중앙 행정청',
    description:
      '루미나스 왕국의 거대한 백색 성벽 수도. 국왕의 왕좌가 자리하고 있으며 대륙 각지에서 모인 사절단과 기사들로 붐비는 정치적 중심지입니다.',
  },

  // 3. Foreign Powers & Strongholds
  {
    id: 'fortress_baran',
    name: '🦅 바란하임 흑철 요새',
    nationId: 'valdor_empire',
    type: 'fortress',
    x: 360,
    y: 300,
    rulerName: '황제 블라디미르 1세',
    title: '발도르 제국 총사령관',
    level: 5,
    defense: 98,
    economy: 80,
    specialty: '흑철 공성병기, 중장 기병단, 군사 훈련소',
    description:
      '발도르 제국의 거대한 수도이자 난공불락의 군사 요새. 거대한 용광로의 연기가 끊이지 않으며 제국의 대군이 집결하는 곳입니다.',
  },
  {
    id: 'fief_iron_gate',
    name: '제국 전방 감시루',
    nationId: 'valdor_empire',
    type: 'fortress',
    x: 520,
    y: 390,
    rulerName: '장군 크루거',
    title: '남부 원정군 선봉장',
    level: 4,
    defense: 70,
    economy: 30,
    specialty: '정찰 요격대, 쇠뇌 방벽',
    description:
      '왕국 국경과 마주보고 있는 제국의 전방 요새. 국경 분쟁의 불씨가 언제든 튈 수 있는 위험 지역입니다.',
  },
  {
    id: 'port_venecia',
    name: '⚖️ 베네치아 자유항',
    nationId: 'free_republic',
    type: 'trade_port',
    x: 430,
    y: 920,
    rulerName: '의장 카스파 론',
    title: '공화국 최고 통상사절',
    level: 5,
    defense: 60,
    economy: 100,
    specialty: '세계 해상 무역, 향신료, 용병 길드',
    description:
      '남부 해안을 호령하는 공화국의 거대한 항구 도시. 온갖 희귀한 보물과 외국의 용병들이 오가는 대륙의 황금 창고입니다.',
  },
  {
    id: 'city_teldrasil',
    name: '🌿 세계수 텔드라실',
    nationId: 'sylvana_federation',
    type: 'capital',
    x: 1320,
    y: 450,
    rulerName: '대장로 엘로라 에델',
    title: '영목의 수호자',
    level: 5,
    defense: 85,
    economy: 70,
    specialty: '생명의 비약, 엘프 궁술단, 고대 마법',
    description:
      '하늘을 찌를 듯 솟아오른 거대한 세계수 주변에 형성된 삼림 연방의 수도. 숲의 정령들과 조화롭게 살아가는 평화의 성지입니다.',
  },
  {
    id: 'fief_sylva_border',
    name: '초록 안개 국경초소',
    nationId: 'sylvana_federation',
    type: 'neighbor',
    x: 1040,
    y: 530,
    rulerName: '순찰대장 아리엘',
    title: '삼림 연방 서부 순찰대',
    level: 3,
    defense: 55,
    economy: 45,
    specialty: '약초 무역, 삼림 순찰, 활과 화살',
    description:
      '플레이어 영지의 동쪽 숲길 너머에 위치한 연방의 초소. 상호 불가침 협정에 따라 왕국과 평화로운 친선 관계를 유지하고 있습니다.',
  },
  {
    id: 'holy_solaria',
    name: '☀️ 성도 솔라리아',
    nationId: 'solaris_holy_empire',
    type: 'sanctuary',
    x: 1160,
    y: 980,
    rulerName: '교황 루시우스 3세',
    title: '태양의 대사제',
    level: 5,
    defense: 90,
    economy: 85,
    specialty: '신성 축복, 성기사단 본부, 치유의 샘',
    description:
      '남동부의 순백 대리석으로 지어진 종교 황국의 중심지. 신성한 태양빛이 비추며 광휘의 성기사들이 경건히 기도를 올리는 장소입니다.',
  },
]

export const TERRAIN_FEATURES: MapTerrainFeature[] = [
  // Mountain ranges
  {
    type: 'mountain',
    name: '용의 등뼈 산맥 (Dragonspine)',
    x: 420,
    y: 200,
    width: 320,
    height: 120,
    label: '⛰️ 용의 등뼈 산맥',
  },
  {
    type: 'mountain',
    name: '검은 화강암 협곡',
    x: 740,
    y: 330,
    width: 160,
    height: 90,
    label: '⛰️ 흑강석 협곡',
  },
  // Forests
  {
    type: 'forest',
    name: '영원의 실바나 원시림',
    x: 1100,
    y: 260,
    width: 500,
    height: 440,
    label: '🌲 실바나 원시림',
  },
  {
    type: 'forest',
    name: '미개척 야생수림 (마을 사냥터 인접)',
    x: 880,
    y: 490,
    width: 140,
    height: 160,
    label: '🌲 야생 수림대',
  },
  // Rivers & Seas
  {
    type: 'river',
    name: '루미나스 은빛 대하',
    x: 550,
    y: 480,
    width: 350,
    height: 380,
    label: '🌊 은빛 강',
  },
  {
    type: 'lake',
    name: '거울의 성수호',
    x: 730,
    y: 620,
    width: 90,
    height: 70,
    label: '💧 성수호',
  },
]
